### ISSUE TITLE
Missing super.updateCell() cause updateCell callback never get called

### ISSUE THREAD

**Issue by xiao99xiao** [EurekaCommunity/ViewRow#17]
There is a comment about it but no reason is explained here. Can anyone tell me why? This makes reloading the custom view almost impossible.
```
//  NOTE: super.updateCell() deliberatly not called.
```

**Comment by alldritt** [comment]
This is because the super's updateCell() does things that are incompatible with ViewRow.  For instance, it updates the cell's title in ways that are not helpful.

I have applications using ViewRow that update over time, and I'm not experiencing problems.  I update the custom view's contents directly and have it redraw its self without any problems.
